import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-providers";
import Header from "./(public)/components/header/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning
    >

      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
